mongodb:
  connection-string: mongodb://mongo1:30001,mongo2:30002/config-service?replicaSet=rs0&readPreference=primary&appname=config-service&ssl=false
  database-name: config-service

jms:
  broker:
    url: tcp://localhost:61616
  activemq:
    topic-name: config-service.parameters

logging:
  level:
    com:
      kostylenko:
        config_service:
          config_service_rest:
            domain:
              service: DEBUG

    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

config-provider:
  app-name: config-service
  configs:
    - name: errors
      version: 1.0
      clazz: com.kostylenko.config_service.config_provider.common_config.Message
      beanName: errors
  broker-url: tcp://localhost:61616
  migration:
    enabled: true
    fileLocation: config-service-rest/src/main/resources/default-data.json