mongodb:
  connection-string: mongodb://mongo1:30001,mongo2:30002/config-service?replicaSet=rs0&readPreference=secondaryPreferred&appname=config-service&ssl=false
  database-name: config-service

jms:
  broker:
    url: tcp://localhost:61616
  activemq:
    topic-name: config-service.parameters

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

config-provider:
  app-name: config-service
  configs:
    - name: errors
      version: 1.0
      clazz: com.kostylenko.config_service.config_provider.common_config.Message
      beanName: errors
  broker-url: tcp://localhost:61616