version: '3.8'

services:
  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    ports:
      - "61616:61616" # broker
      - "8161:8161"   # web    http://localhost:8161/admin (admin:admin)

  mongo1:
    image: mongo:4.2
    container_name: mongo1
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "30001" ]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo2:
    image: mongo:4.2
    container_name: mongo2
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "30002" ]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 30002:30002